"use client";

import * as React from "react";
import useSWR, { mutate } from "swr";
import { Plus, Pause, Play, SkipForward, Trash2, Pencil, CalendarClock, Eye, LayoutGrid, List, MoreHorizontal } from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import {
  Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { useConfirm } from "@/components/confirm-provider";
import { useCurrency } from "@/components/currency-provider";
import { RecurringDialog } from "@/components/recurring/recurring-dialog";
import { delJson, patchJson } from "@/lib/fetcher";
import { cn } from "@/lib/utils";

interface RecurringRule {
  id: string;
  name: string;
  type: "INCOME" | "EXPENSE" | "TRANSFER";
  amount: string;
  frequency: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
  interval: number;
  startDate: string;
  endDate: string | null;
  nextRunDate: string;
  status: "ACTIVE" | "PAUSED" | "ENDED";
  description: string | null;
  account: { id: string; name: string } | null;
  toAccount: { id: string; name: string } | null;
  category: { id: string; name: string } | null;
  sipHoldings?: Array<{ id: string; assetClass: string; type: string; name: string }>;
}

interface PreviewItem {
  ruleId: string;
  name: string;
  type: string;
  amount: string;
  date: string;
}

export default function RecurringPage() {
  const { data: rules, isLoading } = useSWR<RecurringRule[]>("/api/recurring");
  const confirm = useConfirm();
  const { formatCurrency } = useCurrency();
  const [createOpen, setCreateOpen] = React.useState(false);
  const [editRule, setEditRule] = React.useState<RecurringRule | null>(null);
  const [previewOpen, setPreviewOpen] = React.useState(false);
  const [viewMode, setViewMode] = React.useState<"grid" | "list">(() => {
    if (typeof window !== "undefined") return (localStorage.getItem("finarc_rec_view") as "grid" | "list") ?? "grid";
    return "grid";
  });
  React.useEffect(() => { localStorage.setItem("finarc_rec_view", viewMode); }, [viewMode]);
  const { data: preview } = useSWR<PreviewItem[]>(previewOpen ? "/api/recurring/preview?months=3" : null);

  const onPause = async (rule: RecurringRule) => {
    const newStatus = rule.status === "ACTIVE" ? "PAUSED" : "ACTIVE";
    try {
      await patchJson(`/api/recurring/${rule.id}`, { status: newStatus });
      toast.success(newStatus === "PAUSED" ? "Rule paused" : "Rule resumed");
      mutate("/api/recurring");
      mutate("/api/commitments/forecast");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update");
    }
  };

  const onSkipNext = async (rule: RecurringRule) => {
    try {
      await patchJson(`/api/recurring/${rule.id}`, { skipDate: rule.nextRunDate });
      toast.success(`Skipped ${format(new Date(rule.nextRunDate), "MMM d, yyyy")}`);
      mutate("/api/recurring");
      mutate("/api/commitments/forecast");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to skip");
    }
  };

  const onDelete = async (rule: RecurringRule) => {
    const ok = await confirm({
      title: `Delete "${rule.name}"?`,
      description: "This removes the recurring rule. Past transactions generated by it will remain.",
      confirmLabel: "Delete",
      tone: "destructive",
    });
    if (!ok) return;
    try {
      await delJson(`/api/recurring/${rule.id}`);
      toast.success("Rule deleted");
      mutate("/api/recurring");
      mutate("/api/commitments/forecast");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete");
    }
  };

  const onMaterialize = async () => {
    try {
      const res = await fetch("/api/recurring/materialize", { method: "POST" });
      const json = await res.json();
      const count = json?.data?.materialized ?? 0;
      toast.success(count > 0 ? `Generated ${count} transaction(s)` : "Nothing due yet");
      mutate(() => true, undefined, { revalidate: true });
    } catch (e) {
      toast.error("Failed to materialize");
    }
  };

  const active = (rules ?? []).filter((r) => r.status === "ACTIVE");
  const paused = (rules ?? []).filter((r) => r.status === "PAUSED");
  const ended = (rules ?? []).filter((r) => r.status === "ENDED");

  return (
    <div className="space-y-6">
      <div className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center">
        <div>
          <h2 className="text-xl font-semibold tracking-tight md:text-2xl">Recurring</h2>
          <p className="text-sm text-muted-foreground">Manage recurring income, expenses, and transfers.</p>
        </div>
        <div className="flex gap-2">
          <div className="flex rounded-md border">
            <Button variant={viewMode === "grid" ? "secondary" : "ghost"} size="icon" className="h-8 w-8 rounded-r-none" onClick={() => setViewMode("grid")}><LayoutGrid className="h-4 w-4" /></Button>
            <Button variant={viewMode === "list" ? "secondary" : "ghost"} size="icon" className="h-8 w-8 rounded-l-none border-l" onClick={() => setViewMode("list")}><List className="h-4 w-4" /></Button>
          </div>
          <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setPreviewOpen(true)}>
            <Eye className="h-4 w-4" /> Preview
          </Button>
          <Button variant="outline" size="sm" className="gap-1.5" onClick={onMaterialize}>
            <CalendarClock className="h-4 w-4" /> Run due now
          </Button>
          <Button size="sm" className="gap-1.5" onClick={() => setCreateOpen(true)}>
            <Plus className="h-4 w-4" /> New rule
          </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="grid gap-3 md:grid-cols-2">{Array.from({ length: 4 }).map((_, i) => (<Skeleton key={i} className="h-[120px]" />))}</div>
      ) : (rules ?? []).length === 0 ? (
        <EmptyState
          icon={<CalendarClock className="h-5 w-5" />}
          title="No recurring rules"
          description="Set up recurring income (salary), expenses (rent, subscriptions), or transfers."
          action={<Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" /> Create rule</Button>}
        />
      ) : (
        <div className="space-y-6">
          {viewMode === "grid" ? (
            <>
              {active.length > 0 && <RuleSection title="Active" rules={active} formatCurrency={formatCurrency} onPause={onPause} onSkipNext={onSkipNext} onEdit={setEditRule} onDelete={onDelete} />}
              {paused.length > 0 && <RuleSection title="Paused" rules={paused} formatCurrency={formatCurrency} onPause={onPause} onSkipNext={onSkipNext} onEdit={setEditRule} onDelete={onDelete} />}
              {ended.length > 0 && <RuleSection title="Ended" rules={ended} formatCurrency={formatCurrency} onPause={onPause} onSkipNext={onSkipNext} onEdit={setEditRule} onDelete={onDelete} />}
            </>
          ) : (
            <Card>
              <CardContent className="px-0 py-0">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Frequency</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                      <TableHead>Next run</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Account</TableHead>
                      <TableHead className="w-10" />
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {(rules ?? []).map((r) => (
                      <TableRow key={r.id}>
                        <TableCell className="font-medium">{r.name}</TableCell>
                        <TableCell><Badge variant={ruleKind(r).variant} className="text-[10px]">{ruleKind(r).label}</Badge></TableCell>
                        <TableCell className="text-sm text-muted-foreground">{r.frequency.toLowerCase()}{r.interval > 1 ? ` (×${r.interval})` : ""}</TableCell>
                        <TableCell className="text-right tabular">{formatCurrency(r.amount)}</TableCell>
                        <TableCell className="text-sm">{r.status === "ACTIVE" ? format(new Date(r.nextRunDate), "MMM d") : "—"}</TableCell>
                        <TableCell><Badge variant={r.status === "ACTIVE" ? "success" : r.status === "PAUSED" ? "warning" : "muted"} className="text-[10px]">{r.status}</Badge></TableCell>
                        <TableCell className="text-sm text-muted-foreground">{r.account?.name ?? "—"}</TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-7 w-7"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem onClick={() => onPause(r)}>{r.status === "ACTIVE" ? "Pause" : "Resume"}</DropdownMenuItem>
                              {r.status === "ACTIVE" && <DropdownMenuItem onClick={() => onSkipNext(r)}>Skip next</DropdownMenuItem>}
                              <DropdownMenuItem onClick={() => setEditRule(r)}>Edit</DropdownMenuItem>
                              <DropdownMenuItem onClick={() => onDelete(r)} className="text-destructive">Delete</DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      <RecurringDialog open={createOpen} onOpenChange={setCreateOpen} />
      <RecurringDialog open={Boolean(editRule)} onOpenChange={(o) => { if (!o) setEditRule(null); }} editRule={editRule} />

      {/* Preview dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-h-[80vh] overflow-y-auto sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Upcoming 3 months</DialogTitle>
            <DialogDescription>Preview of all recurring transactions that will be generated.</DialogDescription>
          </DialogHeader>
          {!preview ? (
            <div className="space-y-2">{Array.from({ length: 5 }).map((_, i) => (<Skeleton key={i} className="h-10" />))}</div>
          ) : preview.length === 0 ? (
            <p className="py-6 text-center text-sm text-muted-foreground">Nothing scheduled.</p>
          ) : (
            <ul className="divide-y max-h-[50vh] overflow-y-auto">
              {preview.map((p, i) => (
                <li key={`${p.ruleId}-${i}`} className="flex items-center justify-between py-2.5 text-sm">
                  <div>
                    <p className="font-medium">{p.name}</p>
                    <p className="text-xs text-muted-foreground">{format(new Date(p.date), "EEE, MMM d, yyyy")}</p>
                  </div>
                  <span className={cn("tabular font-medium", p.type === "INCOME" ? "text-emerald-600" : "text-rose-600")}>
                    {p.type === "INCOME" ? "+" : "-"}{formatCurrency(p.amount)}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

function RuleSection({
  title,
  rules,
  formatCurrency,
  onPause,
  onSkipNext,
  onEdit,
  onDelete,
}: {
  title: string;
  rules: RecurringRule[];
  formatCurrency: (v: number | string | null | undefined) => string;
  onPause: (r: RecurringRule) => void;
  onSkipNext: (r: RecurringRule) => void;
  onEdit: (r: RecurringRule) => void;
  onDelete: (r: RecurringRule) => void;
}) {
  return (
    <section className="space-y-3">
      <div className="flex items-center gap-2">
        <h3 className="text-sm font-medium">{title}</h3>
        <Separator className="flex-1" />
        <span className="text-xs text-muted-foreground">{rules.length}</span>
      </div>
      <div className="grid gap-3 md:grid-cols-2">
        {rules.map((r) => (
          <Card key={r.id}>
            <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2">
              <div>
                <CardDescription className="flex items-center gap-2">
                  <Badge variant={ruleKind(r).variant} className="text-[10px]">{ruleKind(r).label}</Badge>
                  {r.frequency.toLowerCase()}{r.interval > 1 ? ` (every ${r.interval})` : ""}
                </CardDescription>
                <CardTitle className="mt-1 text-base">{r.name}</CardTitle>
              </div>
              <Badge variant={r.status === "ACTIVE" ? "success" : r.status === "PAUSED" ? "warning" : "muted"}>{r.status}</Badge>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="flex items-baseline justify-between">
                <span className="tabular text-xl font-semibold">{formatCurrency(r.amount)}</span>
                <span className="text-xs text-muted-foreground">
                  Next: {r.status === "ACTIVE" ? format(new Date(r.nextRunDate), "MMM d") : "—"}
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                {r.account?.name ?? ""}{r.type === "TRANSFER" && r.toAccount ? ` → ${r.toAccount.name}` : ""}
                {r.category ? ` · ${r.category.name}` : ""}
              </p>
              <div className="flex gap-1 pt-1">
                <Button variant="ghost" size="icon" onClick={() => onPause(r)} aria-label={r.status === "ACTIVE" ? "Pause" : "Resume"}>
                  {r.status === "ACTIVE" ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
                </Button>
                {r.status === "ACTIVE" && (
                  <Button variant="ghost" size="icon" onClick={() => onSkipNext(r)} aria-label="Skip next">
                    <SkipForward className="h-4 w-4" />
                  </Button>
                )}
                <Button variant="ghost" size="icon" onClick={() => onEdit(r)} aria-label="Edit"><Pencil className="h-4 w-4" /></Button>
                <Button variant="ghost" size="icon" onClick={() => onDelete(r)} aria-label="Delete"><Trash2 className="h-4 w-4" /></Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
}

function ruleKind(rule: RecurringRule): { label: string; variant: "success" | "destructive" | "muted" | "warning" } {
  if (rule.sipHoldings?.length) return { label: "Investment", variant: "muted" };
  if (rule.type === "INCOME") return { label: "Income", variant: "success" };
  if (rule.type === "EXPENSE") return { label: "Expense", variant: "destructive" };
  return { label: "Transfer", variant: "muted" };
}
